Filters for products
IntersysConsulting/ingangsters-web pull request #155
Opened 2019-10-15 19:12 UTC by jogadev

2019-10-15 19:26 UTC, JAndresHJ approved these changes

2019-10-15 19:27 UTC, martin-one approved these changes

2019-10-15 19:28 UTC, martin-one requested changes
NW

2019-10-15 19:30 UTC, JAndresHJ requested changes
![image](https://user-images.githubusercontent.com/39096718/66863239-34974480-ef58-11e9-9e08-95840175c1d3.png)
No encuentra la barra de búsqueda

2019-10-15 21:47 UTC, JAndresHJ approved these changes

2019-10-15 22:43 UTC, zkdna approved these changes

2019-10-16 15:00 UTC, martin-one approved these changes

2019-10-16 15:00 UTC, merged