Footer added
IntersysConsulting/ingangsters-web pull request #158
Opened 2019-10-16 18:09 UTC by zkdna

2019-10-16 18:14 UTC, jogadev submitted a review, later dismissed

2019-10-16 18:37 UTC, martin-one requested changes
Hay que agregar el footer para que sea parte del UI.

![imagen](https://user-images.githubusercontent.com/13110894/66948238-eb0f2e00-f019-11e9-80e4-d50bafb39a00.png)

Tambien me parece que para mobiles la letra se hace mas pequeña, esto es para iphone 6 (4.7 inch), si lo pones en un iPhone SE (4 inch) se ve aun mas pequeño.
![imagen](https://user-images.githubusercontent.com/13110894/66948356-26a9f800-f01a-11e9-9237-5f1585a3f1ab.png)

2019-10-16 20:09 UTC, martin-one approved these changes

2019-10-17 13:28 UTC, sofia-robles-Intersys approved these changes

2019-10-17 13:30 UTC, merged