Banner
IntersysConsulting/ingangsters-web pull request #159
Opened 2019-10-17 14:43 UTC by zkdna

2019-10-17 17:01 UTC, sofia-robles-Intersys requested changes
En mobile se ve muy pequeño el banner y se ve un poco extraño.
![image](https://user-images.githubusercontent.com/53873420/67030794-c8dae600-f0d5-11e9-92d7-10104bc12943.png)

2019-10-18 18:38 UTC, martin-one submitted a review, later dismissed

2019-10-18 18:40 UTC, jogadev submitted a review, later dismissed

2019-10-21 13:24 UTC, sofia-robles-Intersys approved these changes

2019-10-21 14:55 UTC, jogadev approved these changes

2019-10-21 14:59 UTC, merged