Notifications added
IntersysConsulting/ingangsters-web pull request #169
Opened 2019-10-28 16:15 UTC by zkdna

Notifications were placed in almost all the required places

2019-10-28 16:42 UTC, jogadev requested changes
Revisa los conflictos, ademas de que hay algunos console.log que ya no tienen caso teniendo la notificacion.

2019-10-29 14:57 UTC, sofia-robles-Intersys submitted a review, later dismissed

2019-10-29 17:38 UTC, JAndresHJ submitted a review, later dismissed

2019-10-29 17:45 UTC, JAndresHJ approved these changes

2019-10-29 17:46 UTC, sofia-robles-Intersys approved these changes

2019-10-29 17:49 UTC, jogadev approved these changes

2019-10-29 17:49 UTC, merged