Update product finished
IntersysConsulting/ingangsters-web pull request #71
Opened 2019-09-23 20:35 UTC by jogadev

Now supports images, code refactored for cleaner component.

2019-09-23 20:56 UTC, martin-one requested changes
![imagen](https://user-images.githubusercontent.com/13110894/65462076-a62d1880-de1a-11e9-88b5-1b7e02a896be.png)

Esto deberia de funcionar o aun no?

2019-09-24 16:02 UTC, jogadev commented
> ![imagen](https://user-images.githubusercontent.com/13110894/65462076-a62d1880-de1a-11e9-88b5-1b7e02a896be.png)
> 
> Esto deberia de funcionar o aun no?

Now it does

2019-09-24 16:05 UTC, martin-one approved these changes

2019-09-24 16:16 UTC, zkdna approved these changes

2019-09-24 16:18 UTC, merged