Modal for admin and user/guest
IntersysConsulting/ingangsters-web pull request #74
Opened 2019-09-26 16:39 UTC by zkdna

Shadow were removed, and the modal were implemented from the icon button.

2019-09-26 16:45 UTC, sofia-robles-Intersys requested changes
En el archive Routes.js cambió el AdminRoute por Route y me parece que debe ser AdminRoute.
Lineas 30 y 31.

AdminRoute path="/admin/product/:id" component={Product} 
 AdminRoute path="/admin/product" exact component={AdminPage}

2019-09-26 16:54 UTC, martin-one requested changes
Eliminar console.log() que ya no se usen.

Los que vi fueron authenticated: false/true
e imprimir productos en el main.

2019-09-26 17:32 UTC, JAndresHJ requested changes
![image](https://user-images.githubusercontent.com/39096718/65710981-9cddbf00-e059-11e9-9315-2ba91b6d3ff3.png)
Creo que esto se puede resumir a una sola clase. Y también podrías ponerle nombres a las clases más descriptivos, ejemplo hay clases que son button-one y otra que es buttonOne

2019-09-26 21:49 UTC, martin-one submitted a review, later dismissed

2019-09-26 21:56 UTC, jogadev requested changes
![image](https://user-images.githubusercontent.com/48494652/65727792-72522d00-e07e-11e9-86b0-b31893122447.png)

Este hover se ve raro, hay que quitar esa linea negra que se ve, yo le pondría `text-decoration:none !important`

2019-09-27 14:31 UTC, sergio180194 commented
<img width="1680" alt="Screen Shot 2019-09-27 at 9 26 12 AM" src="https://user-images.githubusercontent.com/31085282/65777232-4039dd00-e109-11e9-9e73-100b58aacb56.png">

Problablemente este no es problema tuyo pero, existe un espacio en blanco en esta vista entre el navbar y el borde de la ventana

2019-09-27 14:42 UTC, sergio180194 approved these changes

2019-09-27 14:52 UTC, jogadev approved these changes

2019-09-27 14:59 UTC, martin-one approved these changes

2019-09-27 15:01 UTC, sofia-robles-Intersys approved these changes

2019-09-27 15:01 UTC, merged