Route for invalid addresses
IntersysConsulting/ingangsters-web pull request #82
Opened 2019-09-27 21:38 UTC by zkdna

Page "404" added

2019-09-27 22:06 UTC, martin-one requested changes
En mobile se ve muy chico el texto y boton, no?
![imagen](https://user-images.githubusercontent.com/13110894/65804896-291adf80-e149-11e9-8868-facca3f63090.png)

2019-09-27 22:10 UTC, martin-one requested changes
Otra cosa, hay que poner esta pagina dentro de UI, para no hacer carpetas de mas.

![imagen](https://user-images.githubusercontent.com/13110894/65805005-a6465480-e149-11e9-9bb3-36e0e744fddd.png)

2019-09-30 15:48 UTC, martin-one approved these changes

2019-09-30 15:55 UTC, sofia-robles-Intersys approved these changes

2019-09-30 15:57 UTC, merged