Order summary
IntersysConsulting/ingangsters-web pull request #90
Opened 2019-09-30 22:16 UTC by jogadev

Now uses actual cart data

2019-09-30 22:44 UTC, JAndresHJ approved these changes
La función loadCartData se puede utilizar con redux para no tenerla en este componente y en el del carrito. Por ahora así queda porque el demo ya es en estos días

2019-09-30 22:48 UTC, JAndresHJ requested changes
La función loadCartData se puede utilizar con redux para no tenerla en este componente y en el del carrito.

2019-10-01 14:35 UTC, zkdna approved these changes

2019-10-01 15:14 UTC, martin-one approved these changes

2019-10-01 15:14 UTC, merged